#database:
  # the name of your JDBC driver
 # driverClass: org.postgresql.Driver
  # the username
#  user: postgres
  # the password
#  password: admin
  # the JDBC URL
  #url: jdbc:h2:./target/example
#  url: jdbc:postgresql://localhost:5432/sighting


# Database settings.
database:

  # the name of your JDBC driver
  driverClass: org.h2.Driver

  # the username
  user: sa

  # the password
  password: sa

  # the JDBC URL
  url: jdbc:h2:./target/example
  
  
logging:
  level: DEBUG
  loggers:
    io.dropwizard: INFO
    org.eclipse.jetty: INFO
  appenders:
    - type: console
